name: dev-check

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.10
      - name: Install flake8
        run: pip3 install flake8
          pip3 install pytest
          make install
      - namae: Run linter
      - run: make lint
      
      - name: Run Tests
        run: make pytest

      - name: Code Coverage
        uses: paambaati/codeclimate-action@v3.0.0 
        env:
          CODECLIMATE: ${{ secrets.CODECLIMATE }}
        with:
          coverageCommand: make test-coverage
          debug: true