name: dev-check

on:  push

jobs: 

  build:
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.10
      # Ставим зависимости
      - run: pip install poetry flake8
            pip install pytest
      # Запускаем линтер
      - uses: actions/checkout@v3
        run: make lint
      # Запускаем тесты
      # у шагов может быть имя, иногда это помогает отладке
      # имя выводится на Github при просмотре сборки
      - name: make tests
        run: make test 
