name: dev-check

on:  push

jobs: 

  build:
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/setup-python@v1
        with:
          python-version: 3.10.10
      # Ставим зависимости
      - run: pip install poetry flake8
            pip install pytest
            make install
      # Запускаем линтер
      - uses: actions/checkout@v3
      - run: make lint
      # Запускаем тесты
      - uses: actions/checkout@v3
      - name: make tests
        run: make test 
