name: lint

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.6
          architecture: x64
      - uses: actions/checkout@v3
      - run: make lint